name: Run tests
on: [pull_request]
jobs:
  CommonTests:
    strategy:
        fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Pester
      run: |
        Install-Module Pester -Force -Scope CurrentUser -RequiredVersion 4.10.1
        Install-Module Assert -Force -Scope CurrentUser
        shell: pwsh
    - name: Run tests
      
      run: |
        Import-Module Pester
        Import-Module Assert 
        Invoke-Pester -EnableExit
        shell: pwsh  